SELECT 
M.MEMBER_NAME,
R.REVIEW_TEXT,
TO_CHAR(R.REVIEW_DATE, 'YYYY-MM-DD') as REVIEW_DATE
  FROM MEMBER_PROFILE M NATURAL JOIN
       (
        SELECT MEMBER_ID,
           DENSE_RANK() over (ORDER BY COUNT(MEMBER_ID) DESC) as RANK 
          FROM REST_REVIEW
         GROUP BY MEMBER_ID
       ) 
    A NATURAL JOIN 
    REST_REVIEW R
    
 WHERE A.RANK = 1
 ORDER BY REVIEW_DATE, REVIEW_TEXT